// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsmQl4bCItrpTaMp6ahkTnNiuKvbGo8g8',
    appId: '1:556271392691:web:f734ad612ca7c8ec5cddc6',
    messagingSenderId: '556271392691',
    projectId: 'cabtale-7',
    authDomain: 'cabtale-7.firebaseapp.com',
    storageBucket: 'cabtale-7.firebasestorage.app',
    measurementId: 'G-KQ5Q20WRCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPo6PTAcXY_lbT5YYwD82NWNxOO4lPHmk',
    appId: '1:556271392691:android:b6e3d0dba26adf625cddc6',
    messagingSenderId: '556271392691',
    projectId: 'cabtale-7',
    storageBucket: 'cabtale-7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaDWZScqIbN7rttzNUZF6WDdnXfzuA7uo',
    appId: '1:556271392691:ios:aa55215d0090d0cf5cddc6',
    messagingSenderId: '556271392691',
    projectId: 'cabtale-7',
    storageBucket: 'cabtale-7.firebasestorage.app',
    iosBundleId: 'com.cabtale.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaDWZScqIbN7rttzNUZF6WDdnXfzuA7uo',
    appId: '1:556271392691:ios:587384b3619dbb865cddc6',
    messagingSenderId: '556271392691',
    projectId: 'cabtale-7',
    storageBucket: 'cabtale-7.firebasestorage.app',
    iosBundleId: 'com.sixamtech.ridesharinguser.rideSharingUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsmQl4bCItrpTaMp6ahkTnNiuKvbGo8g8',
    appId: '1:556271392691:web:0813d285599785305cddc6',
    messagingSenderId: '556271392691',
    projectId: 'cabtale-7',
    authDomain: 'cabtale-7.firebaseapp.com',
    storageBucket: 'cabtale-7.firebasestorage.app',
    measurementId: 'G-220L0Z0F0M',
  );

}